### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by jaimovier** [echo-lab/live-writing-osc#11]
Edit the font size from OSC... ideally for different words in the text

**Comment by panavrin** [comment]
Would font size changes dynamically? It is easy to set a font size of any text that is not yet added but changing the size of the already added text is not.

**Comment by jaimovier** [comment]
We can try the easy solution first. I think that should work, changing the size before addition.

**Comment by panavrin** [comment]
I added a osc message called `/fontscale` so that you can set a scale factor before adding a word. (instead of specifying the scale of every word that you add) 

However, this may look different from what you expected because the current livewriting editor uses the fixed span per each character (regardless of the size of the letter) - you will see what I mean when you try `/fontscale 50 (or bigger)` 

I find this more interesting personally but if you want more traditional look (e.g. each letter is readable and does not overlap with each other), let me know that needs some revision.
